[template]
exclude = [
    "target/**",
    "Cargo.lock",
    ".git/**",
    "end2end/playwright-report/**",
    "end2end/test-results/**",
    "end2end/node_modules/**",
    "end2end/playwright/.cache/**",
    "README.md",
]

[placeholders.operating_system]
type = "string"
prompt = "Operating system (windows/linux/macos)"
choices = ["windows", "linux/macos"]
default = "linux/macos"

[conditional.'operating_system == "windows"']
build_script = ".\\build-binaries.ps1"

[conditional.'operating_system == "linux/macos"']
build_script = "./build-binaries.sh"
