[template]
exclude = [
    "target/**",
    "Cargo.lock",
    ".git/**",
    "end2end/playwright-report/**",
    "end2end/test-results/**",
    "end2end/node_modules/**",
    "end2end/playwright/.cache/**",
    "README.md",
    "src-tauri/icons/**",
    "public/favicon.ico",
]
